### ISSUE TITLE
Wordfence Scanning this plugin as Critical issue (Need to Fix)

### ISSUE THREAD

**Issue by creativealt** [wp-activators/wordfence-activator#1]
Filename: ------/wp-content/plugins/wordfence-activator-1.3.0/wordfence-activator.php
File Type: Not a core, theme, or plugin file from wordpress.org.
Details: This file appears to be installed or modified by a hacker to perform malicious activity. If you know about this file you can choose to ignore it to exclude it from future scans. The matched text in this file is: <?php\x0a/**\x0a * @wordpress-plugin\x0a * Plugin Name: Wordfence Security Activator\x0a * Plugin URI: https://github.com/wp-activators/wordfence-activator\x0a * Description: Wordfence Security Pl...

The issue type is: Suspicious:PHP/activator.13966
Description: Plugin Activator script

**Comment by mohamedhk2** [comment]
This issue is fixed in [v1.4.0](https://github.com/mohamedhk2/wordfence-activator/releases/latest)
